export interface Question {
  id: number;
  word: string;
  hint: string;
  category: 'Hewan' | 'Buah' | 'Tubuh Manusia';
  englishTag: string;
}

export const QUESTIONS: Question[] = [
  // --- HEWAN (34) ---
  { id: 1, word: 'GAJAH', hint: 'Hewan besar dengan belalai panjang.', category: 'Hewan', englishTag: 'elephant' },
  { id: 2, word: 'JERAPAH', hint: 'Hewan dengan leher sangat panjang.', category: 'Hewan', englishTag: 'giraffe' },
  { id: 3, word: 'KUCING', hint: 'Hewan peliharaan yang bunyinya meong.', category: 'Hewan', englishTag: 'cat' },
  { id: 4, word: 'ANJING', hint: 'Hewan yang dikenal sebagai sahabat manusia.', category: 'Hewan', englishTag: 'dog' },
  { id: 5, word: 'HARIMAU', hint: 'Kucing besar bergaris-garis.', category: 'Hewan', englishTag: 'tiger' },
  { id: 6, word: 'SINGA', hint: 'Raja hutan yang memiliki rambut lebat di leher (jantan).', category: 'Hewan', englishTag: 'lion' },
  { id: 7, word: 'ZEBRA', hint: 'Hewan berkuda dengan pola hitam putih.', category: 'Hewan', englishTag: 'zebra' },
  { id: 8, word: 'PANDA', hint: 'Hewan pemakan bambu dari Tiongkok.', category: 'Hewan', englishTag: 'panda' },
  { id: 9, word: 'KOALA', hint: 'Hewan Australia yang suka makan daun eukaliptus.', category: 'Hewan', englishTag: 'koala' },
  { id: 10, word: 'KANGURU', hint: 'Hewan yang membawa anaknya di kantong.', category: 'Hewan', englishTag: 'kangaroo' },
  { id: 11, word: 'KOMODO', hint: 'Kadal terbesar di dunia dari Indonesia.', category: 'Hewan', englishTag: 'komodo dragon' },
  { id: 12, word: 'KUDA', hint: 'Hewan yang sering digunakan untuk menarik delman.', category: 'Hewan', englishTag: 'horse' },
  { id: 13, word: 'SAPI', hint: 'Hewan ternak penghasil susu.', category: 'Hewan', englishTag: 'cow' },
  { id: 14, word: 'KAMBING', hint: 'Hewan yang sering dikurbankan, bunyinya mbek.', category: 'Hewan', englishTag: 'goat' },
  { id: 15, word: 'AYAM', hint: 'Hewan unggas yang berkokok di pagi hari.', category: 'Hewan', englishTag: 'chicken' },
  { id: 16, word: 'BEBEK', hint: 'Hewan yang jalannya megal-megol.', category: 'Hewan', englishTag: 'duck' },
  { id: 17, word: 'BURUNG', hint: 'Hewan yang memiliki sayap dan bisa terbang.', category: 'Hewan', englishTag: 'bird' },
  { id: 18, word: 'IKAN', hint: 'Hewan yang bernapas menggunakan insang di air.', category: 'Hewan', englishTag: 'fish' },
  { id: 19, word: 'PAUS', hint: 'Mamalia air yang sangat besar.', category: 'Hewan', englishTag: 'whale' },
  { id: 20, word: 'HIU', hint: 'Predator laut dengan gigi tajam.', category: 'Hewan', englishTag: 'shark' },
  { id: 21, word: 'LUMBA-LUMBA', hint: 'Mamalia cerdas yang suka menolong manusia di laut.', category: 'Hewan', englishTag: 'dolphin' },
  { id: 22, word: 'KURA-KURA', hint: 'Hewan yang membawa rumahnya di punggung.', category: 'Hewan', englishTag: 'turtle' },
  { id: 23, word: 'KELINCI', hint: 'Hewan bertelinga panjang yang suka makan wortel.', category: 'Hewan', englishTag: 'rabbit' },
  { id: 24, word: 'TIKUS', hint: 'Hewan pengerat yang sering ada di selokan.', category: 'Hewan', englishTag: 'mouse' },
  { id: 25, word: 'HAMSTER', hint: 'Hewan pengerat kecil yang sering dipelihara.', category: 'Hewan', englishTag: 'hamster' },
  { id: 26, word: 'MUSANG', hint: 'Hewan malam yang sering mencuri ayam.', category: 'Hewan', englishTag: 'weasel' },
  { id: 27, word: 'SERIGALA', hint: 'Anjing hutan yang melolong saat bulan purnama.', category: 'Hewan', englishTag: 'wolf' },
  { id: 28, word: 'BERUANG', hint: 'Hewan besar yang suka makan madu.', category: 'Hewan', englishTag: 'bear' },
  { id: 29, word: 'RUSA', hint: 'Hewan yang memiliki tanduk bercabang.', category: 'Hewan', englishTag: 'deer' },
  { id: 30, word: 'BADAK', hint: 'Hewan berkulit tebal dengan cula di hidung.', category: 'Hewan', englishTag: 'rhino' },
  { id: 31, word: 'KUDA NIL', hint: 'Hewan besar yang menghabiskan waktu di air.', category: 'Hewan', englishTag: 'hippo' },
  { id: 32, word: 'UNTA', hint: 'Hewan padang pasir dengan punuk di punggung.', category: 'Hewan', englishTag: 'camel' },
  { id: 33, word: 'MONYET', hint: 'Hewan primata yang suka makan pisang.', category: 'Hewan', englishTag: 'monkey' },
  { id: 34, word: 'ORANGUTAN', hint: 'Primata besar berambut kemerahan asli Indonesia.', category: 'Hewan', englishTag: 'orangutan' },

  // --- BUAH (34) ---
  { id: 35, word: 'APEL', hint: 'Buah merah atau hijau yang renyah.', category: 'Buah', englishTag: 'apple' },
  { id: 36, word: 'MANGGA', hint: 'Buah manis dengan biji besar di tengahnya.', category: 'Buah', englishTag: 'mango' },
  { id: 37, word: 'PISANG', hint: 'Buah kuning panjang kegemaran monyet.', category: 'Buah', englishTag: 'banana' },
  { id: 38, word: 'DURIAN', hint: 'Raja buah dengan kulit berduri tajam.', category: 'Buah', englishTag: 'durian' },
  { id: 39, word: 'JERUK', hint: 'Buah bulat kaya vitamin C.', category: 'Buah', englishTag: 'orange fruit' },
  { id: 40, word: 'ANGGUR', hint: 'Buah kecil bulat yang tumbuh merambat.', category: 'Buah', englishTag: 'grapes' },
  { id: 41, word: 'SEMANGKA', hint: 'Buah besar dengan isi merah dan banyak air.', category: 'Buah', englishTag: 'watermelon' },
  { id: 42, word: 'MELON', hint: 'Buah bulat dengan kulit berjaring.', category: 'Buah', englishTag: 'melon' },
  { id: 43, word: 'NANAS', hint: 'Buah bersisik dengan mahkota di atasnya.', category: 'Buah', englishTag: 'pineapple' },
  { id: 44, word: 'PEPAYA', hint: 'Buah lonjong dengan biji hitam kecil banyak.', category: 'Buah', englishTag: 'papaya' },
  { id: 45, word: 'JAMBU', hint: 'Ada yang air, ada yang biji.', category: 'Buah', englishTag: 'guava' },
  { id: 46, word: 'RAMBUTAN', hint: 'Buah dengan kulit berambut.', category: 'Buah', englishTag: 'rambutan' },
  { id: 47, word: 'SALAK', hint: 'Buah dengan kulit bersisik seperti ular.', category: 'Buah', englishTag: 'snake fruit' },
  { id: 48, word: 'MANGGIS', hint: 'Ratu buah dengan isi putih bersih.', category: 'Buah', englishTag: 'mangosteen' },
  { id: 49, word: 'ALPUKAT', hint: 'Buah dengan lemak sehat, sering dijadikan jus.', category: 'Buah', englishTag: 'avocado' },
  { id: 50, word: 'STROBERI', hint: 'Buah kecil merah berbintik.', category: 'Buah', englishTag: 'strawberry' },
  { id: 51, word: 'KELAPA', hint: 'Buah dengan air dan daging putih di dalamnya.', category: 'Buah', englishTag: 'coconut' },
  { id: 52, word: 'KURMA', hint: 'Buah manis yang identik dengan bulan Ramadan.', category: 'Buah', englishTag: 'dates fruit' },
  { id: 53, word: 'KIWI', hint: 'Buah hijau kecil berbulu halus.', category: 'Buah', englishTag: 'kiwi fruit' },
  { id: 54, word: 'LECI', hint: 'Buah kecil manis dengan kulit merah tipis.', category: 'Buah', englishTag: 'lychee' },
  { id: 55, word: 'NAGA', hint: 'Buah dengan kulit bersisik merah dan isi penuh biji kecil.', category: 'Buah', englishTag: 'dragon fruit' },
  { id: 56, word: 'PIR', hint: 'Buah renyah berbentuk lonjong di bawah.', category: 'Buah', englishTag: 'pear' },
  { id: 57, word: 'DELIMA', hint: 'Buah dengan isi butiran merah banyak.', category: 'Buah', englishTag: 'pomegranate' },
  { id: 58, word: 'MARKISA', hint: 'Buah asam manis dengan banyak biji berlendir.', category: 'Buah', englishTag: 'passion fruit' },
  { id: 59, word: 'SAWO', hint: 'Buah cokelat manis dengan kulit tipis.', category: 'Buah', englishTag: 'sapodilla' },
  { id: 60, word: 'SIRSAK', hint: 'Buah hijau berduri lunak dengan isi putih asam manis.', category: 'Buah', englishTag: 'soursop' },
  { id: 61, word: 'KEDONDONG', hint: 'Buah hijau asam dengan biji berserabut.', category: 'Buah', englishTag: 'ambarella' },
  { id: 62, word: 'BELIMBING', hint: 'Buah yang jika dipotong melintang berbentuk bintang.', category: 'Buah', englishTag: 'starfruit' },
  { id: 63, word: 'COKELAT', hint: 'Berasal dari biji kakao.', category: 'Buah', englishTag: 'cacao' },
  { id: 64, word: 'NANGKA', hint: 'Buah besar dengan aroma tajam dan isi kuning.', category: 'Buah', englishTag: 'jackfruit' },
  { id: 65, word: 'CEMPEDAK', hint: 'Mirip nangka tapi aromanya lebih kuat.', category: 'Buah', englishTag: 'cempedak' },
  { id: 66, word: 'KESEMEK', hint: 'Buah yang sering disebut berbedak.', category: 'Buah', englishTag: 'persimmon' },
  { id: 67, word: 'MATOA', hint: 'Buah khas Papua dengan rasa campuran durian dan rambutan.', category: 'Buah', englishTag: 'matoa fruit' },
  { id: 68, word: 'JAMBU BIJI', hint: 'Buah yang sering digunakan untuk penderita demam berdarah.', category: 'Buah', englishTag: 'guava' },

  // --- TUBUH MANUSIA (34) ---
  { id: 69, word: 'MATA', hint: 'Alat indra untuk melihat.', category: 'Tubuh Manusia', englishTag: 'eye' },
  { id: 70, word: 'HIDUNG', hint: 'Alat indra untuk mencium bau.', category: 'Tubuh Manusia', englishTag: 'nose' },
  { id: 71, word: 'TELINGA', hint: 'Alat indra untuk mendengar.', category: 'Tubuh Manusia', englishTag: 'ear' },
  { id: 72, word: 'MULUT', hint: 'Tempat masuknya makanan ke tubuh.', category: 'Tubuh Manusia', englishTag: 'mouth' },
  { id: 73, word: 'GIGI', hint: 'Digunakan untuk mengunyah makanan.', category: 'Tubuh Manusia', englishTag: 'teeth' },
  { id: 74, word: 'LIDAH', hint: 'Alat indra pengecap rasa.', category: 'Tubuh Manusia', englishTag: 'tongue' },
  { id: 75, word: 'TANGAN', hint: 'Anggota tubuh untuk memegang barang.', category: 'Tubuh Manusia', englishTag: 'hand' },
  { id: 76, word: 'KAKI', hint: 'Anggota tubuh untuk berjalan.', category: 'Tubuh Manusia', englishTag: 'foot' },
  { id: 77, word: 'JARI', hint: 'Ujung dari tangan atau kaki.', category: 'Tubuh Manusia', englishTag: 'finger' },
  { id: 78, word: 'KEPALA', hint: 'Bagian teratas tubuh manusia.', category: 'Tubuh Manusia', englishTag: 'head' },
  { id: 79, word: 'RAMBUT', hint: 'Mahkota yang tumbuh di kepala.', category: 'Tubuh Manusia', englishTag: 'hair' },
  { id: 80, word: 'LEHER', hint: 'Penghubung kepala dan badan.', category: 'Tubuh Manusia', englishTag: 'neck' },
  { id: 81, word: 'DADA', hint: 'Bagian depan tubuh di bawah leher.', category: 'Tubuh Manusia', englishTag: 'chest' },
  { id: 82, word: 'PERUT', hint: 'Tempat lambung berada.', category: 'Tubuh Manusia', englishTag: 'stomach' },
  { id: 83, word: 'PUNGGUNG', hint: 'Bagian belakang tubuh.', category: 'Tubuh Manusia', englishTag: 'back body' },
  { id: 84, word: 'BAHU', hint: 'Tempat menyandarkan tas.', category: 'Tubuh Manusia', englishTag: 'shoulder' },
  { id: 85, word: 'LUTUT', hint: 'Sambungan di tengah kaki.', category: 'Tubuh Manusia', englishTag: 'knee' },
  { id: 86, word: 'SIKUT', hint: 'Sambungan di tengah lengan.', category: 'Tubuh Manusia', englishTag: 'elbow' },
  { id: 87, word: 'JANTUNG', hint: 'Organ pemompa darah.', category: 'Tubuh Manusia', englishTag: 'heart organ' },
  { id: 88, word: 'PARU-PARU', hint: 'Organ utama untuk bernapas.', category: 'Tubuh Manusia', englishTag: 'lungs' },
  { id: 89, word: 'HATI', hint: 'Organ penyaring racun dalam tubuh.', category: 'Tubuh Manusia', englishTag: 'liver organ' },
  { id: 90, word: 'LAMBUNG', hint: 'Tempat pencernaan makanan secara kimiawi.', category: 'Tubuh Manusia', englishTag: 'stomach organ' },
  { id: 91, word: 'OTAK', hint: 'Pusat kendali seluruh tubuh.', category: 'Tubuh Manusia', englishTag: 'brain' },
  { id: 92, word: 'GINJAL', hint: 'Organ penyaring darah berbentuk seperti kacang.', category: 'Tubuh Manusia', englishTag: 'kidneys' },
  { id: 93, word: 'DARAH', hint: 'Cairan merah dalam tubuh.', category: 'Tubuh Manusia', englishTag: 'blood' },
  { id: 94, word: 'TULANG', hint: 'Rangka keras penopang tubuh.', category: 'Tubuh Manusia', englishTag: 'bone' },
  { id: 95, word: 'KULIT', hint: 'Indra peraba dan pelindung terluar tubuh.', category: 'Tubuh Manusia', englishTag: 'skin' },
  { id: 96, word: 'KUKU', hint: 'Bagian keras di ujung jari.', category: 'Tubuh Manusia', englishTag: 'nail' },
  { id: 97, word: 'ALIS', hint: 'Rambut di atas mata.', category: 'Tubuh Manusia', englishTag: 'eyebrow' },
  { id: 98, word: 'BULU MATA', hint: 'Melindungi mata dari debu.', category: 'Tubuh Manusia', englishTag: 'eyelashes' },
  { id: 99, word: 'GUSI', hint: 'Tempat gigi tertanam.', category: 'Tubuh Manusia', englishTag: 'gums' },
  { id: 100, word: 'TENGGOROKAN', hint: 'Saluran pernapasan dan pencernaan di leher.', category: 'Tubuh Manusia', englishTag: 'throat' },
  { id: 101, word: 'USUS', hint: 'Saluran panjang tempat penyerapan sari makanan.', category: 'Tubuh Manusia', englishTag: 'intestine' },
  { id: 102, word: 'PIPI', hint: 'Bagian wajah di samping hidung.', category: 'Tubuh Manusia', englishTag: 'cheek' },
];
