export interface Question {
  id: number;
  word: string;
  hint: string;
  category: 'Hewan' | 'Buah' | 'Tubuh Manusia';
}

export const QUESTIONS: Question[] = [
  // --- HEWAN (34) ---
  { id: 1, word: 'GAJAH', hint: 'Hewan besar dengan belalai panjang.', category: 'Hewan' },
  { id: 2, word: 'JERAPAH', hint: 'Hewan dengan leher sangat panjang.', category: 'Hewan' },
  { id: 3, word: 'KUCING', hint: 'Hewan peliharaan yang bunyinya meong.', category: 'Hewan' },
  { id: 4, word: 'ANJING', hint: 'Hewan yang dikenal sebagai sahabat manusia.', category: 'Hewan' },
  { id: 5, word: 'HARIMAU', hint: 'Kucing besar bergaris-garis.', category: 'Hewan' },
  { id: 6, word: 'SINGA', hint: 'Raja hutan yang memiliki rambut lebat di leher (jantan).', category: 'Hewan' },
  { id: 7, word: 'ZEBRA', hint: 'Hewan berkuda dengan pola hitam putih.', category: 'Hewan' },
  { id: 8, word: 'PANDA', hint: 'Hewan pemakan bambu dari Tiongkok.', category: 'Hewan' },
  { id: 9, word: 'KOALA', hint: 'Hewan Australia yang suka makan daun eukaliptus.', category: 'Hewan' },
  { id: 10, word: 'KANGURU', hint: 'Hewan yang membawa anaknya di kantong.', category: 'Hewan' },
  { id: 11, word: 'KOMODO', hint: 'Kadal terbesar di dunia dari Indonesia.', category: 'Hewan' },
  { id: 12, word: 'KUDA', hint: 'Hewan yang sering digunakan untuk menarik delman.', category: 'Hewan' },
  { id: 13, word: 'SAPI', hint: 'Hewan ternak penghasil susu.', category: 'Hewan' },
  { id: 14, word: 'KAMBING', hint: 'Hewan yang sering dikurbankan, bunyinya mbek.', category: 'Hewan' },
  { id: 15, word: 'AYAM', hint: 'Hewan unggas yang berkokok di pagi hari.', category: 'Hewan' },
  { id: 16, word: 'BEBEK', hint: 'Hewan yang jalannya megal-megol.', category: 'Hewan' },
  { id: 17, word: 'BURUNG', hint: 'Hewan yang memiliki sayap dan bisa terbang.', category: 'Hewan' },
  { id: 18, word: 'IKAN', hint: 'Hewan yang bernapas menggunakan insang di air.', category: 'Hewan' },
  { id: 19, word: 'PAUS', hint: 'Mamalia air yang sangat besar.', category: 'Hewan' },
  { id: 20, word: 'HIU', hint: 'Predator laut dengan gigi tajam.', category: 'Hewan' },
  { id: 21, word: 'LUMBA-LUMBA', hint: 'Mamalia cerdas yang suka menolong manusia di laut.', category: 'Hewan' },
  { id: 22, word: 'KURA-KURA', hint: 'Hewan yang membawa rumahnya di punggung.', category: 'Hewan' },
  { id: 23, word: 'KELINCI', hint: 'Hewan bertelinga panjang yang suka makan wortel.', category: 'Hewan' },
  { id: 24, word: 'TIKUS', hint: 'Hewan pengerat yang sering ada di selokan.', category: 'Hewan' },
  { id: 25, word: 'HAMSTER', hint: 'Hewan pengerat kecil yang sering dipelihara.', category: 'Hewan' },
  { id: 26, word: 'MUSANG', hint: 'Hewan malam yang sering mencuri ayam.', category: 'Hewan' },
  { id: 27, word: 'SERIGALA', hint: 'Anjing hutan yang melolong saat bulan purnama.', category: 'Hewan' },
  { id: 28, word: 'BERUANG', hint: 'Hewan besar yang suka makan madu.', category: 'Hewan' },
  { id: 29, word: 'RUSA', hint: 'Hewan yang memiliki tanduk bercabang.', category: 'Hewan' },
  { id: 30, word: 'BADAK', hint: 'Hewan berkulit tebal dengan cula di hidung.', category: 'Hewan' },
  { id: 31, word: 'KUDA NIL', hint: 'Hewan besar yang menghabiskan waktu di air.', category: 'Hewan' },
  { id: 32, word: 'UNTA', hint: 'Hewan padang pasir dengan punuk di punggung.', category: 'Hewan' },
  { id: 33, word: 'MONYET', hint: 'Hewan primata yang suka makan pisang.', category: 'Hewan' },
  { id: 34, word: 'ORANGUTAN', hint: 'Primata besar berambut kemerahan asli Indonesia.', category: 'Hewan' },

  // --- BUAH (34) ---
  { id: 35, word: 'APEL', hint: 'Buah merah atau hijau yang renyah.', category: 'Buah' },
  { id: 36, word: 'MANGGA', hint: 'Buah manis dengan biji besar di tengahnya.', category: 'Buah' },
  { id: 37, word: 'PISANG', hint: 'Buah kuning panjang kegemaran monyet.', category: 'Buah' },
  { id: 38, word: 'DURIAN', hint: 'Raja buah dengan kulit berduri tajam.', category: 'Buah' },
  { id: 39, word: 'JERUK', hint: 'Buah bulat kaya vitamin C.', category: 'Buah' },
  { id: 40, word: 'ANGGUR', hint: 'Buah kecil bulat yang tumbuh merambat.', category: 'Buah' },
  { id: 41, word: 'SEMANGKA', hint: 'Buah besar dengan isi merah dan banyak air.', category: 'Buah' },
  { id: 42, word: 'MELON', hint: 'Buah bulat dengan kulit berjaring.', category: 'Buah' },
  { id: 43, word: 'NANAS', hint: 'Buah bersisik dengan mahkota di atasnya.', category: 'Buah' },
  { id: 44, word: 'PEPAYA', hint: 'Buah lonjong dengan biji hitam kecil banyak.', category: 'Buah' },
  { id: 45, word: 'JAMBU', hint: 'Ada yang air, ada yang biji.', category: 'Buah' },
  { id: 46, word: 'RAMBUTAN', hint: 'Buah dengan kulit berambut.', category: 'Buah' },
  { id: 47, word: 'SALAK', hint: 'Buah dengan kulit bersisik seperti ular.', category: 'Buah' },
  { id: 48, word: 'MANGGIS', hint: 'Ratu buah dengan isi putih bersih.', category: 'Buah' },
  { id: 49, word: 'ALPUKAT', hint: 'Buah dengan lemak sehat, sering dijadikan jus.', category: 'Buah' },
  { id: 50, word: 'STROBERI', hint: 'Buah kecil merah berbintik.', category: 'Buah' },
  { id: 51, word: 'KELAPA', hint: 'Buah dengan air dan daging putih di dalamnya.', category: 'Buah' },
  { id: 52, word: 'KURMA', hint: 'Buah manis yang identik dengan bulan Ramadan.', category: 'Buah' },
  { id: 53, word: 'KIWI', hint: 'Buah hijau kecil berbulu halus.', category: 'Buah' },
  { id: 54, word: 'LECI', hint: 'Buah kecil manis dengan kulit merah tipis.', category: 'Buah' },
  { id: 55, word: 'NAGA', hint: 'Buah dengan kulit bersisik merah dan isi penuh biji kecil.', category: 'Buah' },
  { id: 56, word: 'PIR', hint: 'Buah renyah berbentuk lonjong di bawah.', category: 'Buah' },
  { id: 57, word: 'DELIMA', hint: 'Buah dengan isi butiran merah banyak.', category: 'Buah' },
  { id: 58, word: 'MARKISA', hint: 'Buah asam manis dengan banyak biji berlendir.', category: 'Buah' },
  { id: 59, word: 'SAWO', hint: 'Buah cokelat manis dengan kulit tipis.', category: 'Buah' },
  { id: 60, word: 'SIRSAK', hint: 'Buah hijau berduri lunak dengan isi putih asam manis.', category: 'Buah' },
  { id: 61, word: 'KEDONDONG', hint: 'Buah hijau asam dengan biji berserabut.', category: 'Buah' },
  { id: 62, word: 'BELIMBING', hint: 'Buah yang jika dipotong melintang berbentuk bintang.', category: 'Buah' },
  { id: 63, word: 'COKELAT', hint: 'Berasal dari biji kakao.', category: 'Buah' },
  { id: 64, word: 'NANGKA', hint: 'Buah besar dengan aroma tajam dan isi kuning.', category: 'Buah' },
  { id: 65, word: 'CEMPEDAK', hint: 'Mirip nangka tapi aromanya lebih kuat.', category: 'Buah' },
  { id: 66, word: 'KESEMEK', hint: 'Buah yang sering disebut berbedak.', category: 'Buah' },
  { id: 67, word: 'MATOA', hint: 'Buah khas Papua dengan rasa campuran durian dan rambutan.', category: 'Buah' },
  { id: 68, word: 'JAMBU BIJI', hint: 'Buah yang sering digunakan untuk penderita demam berdarah.', category: 'Buah' },

  // --- TUBUH MANUSIA (34) ---
  { id: 69, word: 'MATA', hint: 'Alat indra untuk melihat.', category: 'Tubuh Manusia' },
  { id: 70, word: 'HIDUNG', hint: 'Alat indra untuk mencium bau.', category: 'Tubuh Manusia' },
  { id: 71, word: 'TELINGA', hint: 'Alat indra untuk mendengar.', category: 'Tubuh Manusia' },
  { id: 72, word: 'MULUT', hint: 'Tempat masuknya makanan ke tubuh.', category: 'Tubuh Manusia' },
  { id: 73, word: 'GIGI', hint: 'Digunakan untuk mengunyah makanan.', category: 'Tubuh Manusia' },
  { id: 74, word: 'LIDAH', hint: 'Alat indra pengecap rasa.', category: 'Tubuh Manusia' },
  { id: 75, word: 'TANGAN', hint: 'Anggota tubuh untuk memegang barang.', category: 'Tubuh Manusia' },
  { id: 76, word: 'KAKI', hint: 'Anggota tubuh untuk berjalan.', category: 'Tubuh Manusia' },
  { id: 77, word: 'JARI', hint: 'Ujung dari tangan atau kaki.', category: 'Tubuh Manusia' },
  { id: 78, word: 'KEPALA', hint: 'Bagian teratas tubuh manusia.', category: 'Tubuh Manusia' },
  { id: 79, word: 'RAMBUT', hint: 'Mahkota yang tumbuh di kepala.', category: 'Tubuh Manusia' },
  { id: 80, word: 'LEHER', hint: 'Penghubung kepala dan badan.', category: 'Tubuh Manusia' },
  { id: 81, word: 'DADA', hint: 'Bagian depan tubuh di bawah leher.', category: 'Tubuh Manusia' },
  { id: 82, word: 'PERUT', hint: 'Tempat lambung berada.', category: 'Tubuh Manusia' },
  { id: 83, word: 'PUNGGUNG', hint: 'Bagian belakang tubuh.', category: 'Tubuh Manusia' },
  { id: 84, word: 'BAHU', hint: 'Tempat menyandarkan tas.', category: 'Tubuh Manusia' },
  { id: 85, word: 'LUTUT', hint: 'Sambungan di tengah kaki.', category: 'Tubuh Manusia' },
  { id: 86, word: 'SIKUT', hint: 'Sambungan di tengah lengan.', category: 'Tubuh Manusia' },
  { id: 87, word: 'JANTUNG', hint: 'Organ pemompa darah.', category: 'Tubuh Manusia' },
  { id: 88, word: 'PARU-PARU', hint: 'Organ utama untuk bernapas.', category: 'Tubuh Manusia' },
  { id: 89, word: 'HATI', hint: 'Organ penyaring racun dalam tubuh.', category: 'Tubuh Manusia' },
  { id: 90, word: 'LAMBUNG', hint: 'Tempat pencernaan makanan secara kimiawi.', category: 'Tubuh Manusia' },
  { id: 91, word: 'OTAK', hint: 'Pusat kendali seluruh tubuh.', category: 'Tubuh Manusia' },
  { id: 92, word: 'GINJAL', hint: 'Organ penyaring darah berbentuk seperti kacang.', category: 'Tubuh Manusia' },
  { id: 93, word: 'DARAH', hint: 'Cairan merah dalam tubuh.', category: 'Tubuh Manusia' },
  { id: 94, word: 'TULANG', hint: 'Rangka keras penopang tubuh.', category: 'Tubuh Manusia' },
  { id: 95, word: 'KULIT', hint: 'Indra peraba dan pelindung terluar tubuh.', category: 'Tubuh Manusia' },
  { id: 96, word: 'KUKU', hint: 'Bagian keras di ujung jari.', category: 'Tubuh Manusia' },
  { id: 97, word: 'ALIS', hint: 'Rambut di atas mata.', category: 'Tubuh Manusia' },
  { id: 98, word: 'BULU MATA', hint: 'Melindungi mata dari debu.', category: 'Tubuh Manusia' },
  { id: 99, word: 'GUSI', hint: 'Tempat gigi tertanam.', category: 'Tubuh Manusia' },
  { id: 100, word: 'TENGGOROKAN', hint: 'Saluran pernapasan dan pencernaan di leher.', category: 'Tubuh Manusia' },
  { id: 101, word: 'USUS', hint: 'Saluran panjang tempat penyerapan sari makanan.', category: 'Tubuh Manusia' },
  { id: 102, word: 'PIPI', hint: 'Bagian wajah di samping hidung.', category: 'Tubuh Manusia' },
];
